apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-oct16-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-oct16-1:10571b10bc145d8e6e00b6cb0ef9d98305d15e33@sha256:7375a923193a8d95d0d4c5c1f09cfb22d5128a210e7d7451e2a15e2f13a9f11b # use pre-built to bootstrap 
          name: app-inference
